### ISSUE TITLE
critical 1.0.0 upgrade introduced (undocumented?) breaking change / dependency on puppeteer (Headless Chrome)

### ISSUE THREAD

**Issue by thescientist13** [anthonygore/html-critical-webpack-plugin#14]
as [observed in the webpack v4 upgrade issue](https://github.com/anthonygore/html-critical-webpack-plugin/issues/9#issuecomment-377991102), it seems that as part of the [1.0.0 release of critical](https://github.com/addyosmani/critical/releases/tag/v1.0.0) the package migrated to using Headless Chrome from PhantomJS, which means all build environments  (local, CI, etc) have to have support for [puppeteer](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) or else builds will break silently.

There's not much for the plugin team to do per se as it will be incumbent on consumers to provide the "correct" build time environment, but I think a couple things could be done to prevent future regressions / awareness
1. introducing some basic CI into the project that tests (and fails, ideally) the build when `critical` itself fails
1. Add some documentation in the README about the **puppeteer** dependency

**Comment by thescientist13** [comment]
so with a basic test webpack configuration
```javascript
const ExtractTextWebpackPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackCriticalPlugin = require('./index');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');
const path = require('path');

const OUTPUT_DIR = path.resolve(__dirname, 'build');

module.exports = {
  
  entry: {
    index: './test/cases/generate-critical-css/index.js'
  },

  output: {
    path: OUTPUT_DIR,
    filename: 'html-crtitical-webpack-plugin.js'
  },

  module: {
    rules: [{
      test: /\.css$/,
      use: ExtractTextWebpackPlugin.extract({
        use: ['css-loader']
      })
    }]
  },

  plugins: [
    new HtmlWebpackPlugin(),

    new ExtractTextWebpackPlugin('styles.[chunkhash].css'),
    
    new HtmlWebpackCriticalPlugin({
      base: OUTPUT_DIR,
      src: 'index.html',
      dest: 'index.html',
      inline: true
    })
  ]
};
```

and using bare bones node 8.9.4 [Docker configuration in our repo](https://github.com/thescientist13/html-critical-webpack-plugin/pull/2/files#diff-1d37e48f9ceff6d8030570cd36286a61) (using CircleCI)
```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
```

we can see [the build](https://circleci.com/gh/thescientist13/html-critical-webpack-plugin/9) doesn't complete
<img width="1518" alt="screen shot 2018-04-02 at 2 30 55 pm" src="https://user-images.githubusercontent.com/895923/38209672-1d03b874-3683-11e8-9243-312340016def.png">

for comparison locally I get this output when running the same command (`npm run ci`)
```shell
$ npm run ci

> html-critical-webpack-plugin@1.1.0 ci /Users/owenbuckley/Workspace/github/forks/html-critical-webpack-plugin
> webpack --config ./webpack.config.ci.js

Hash: 6250bf09a859aafabd31
Version: webpack 3.11.0
Time: 1522ms
                           Asset       Size  Chunks             Chunk Names
html-crtitical-webpack-plugin.js    2.92 kB       0  [emitted]  index
 styles.e13c0bda710db7138687.css  329 bytes       0  [emitted]  index
                      index.html  267 bytes          [emitted]
   [0] ./test/cases/generate-critical-css/index.js 21 bytes {0} [built]
   [1] ./test/cases/generate-critical-css/index.css 41 bytes {0} [built]
    + 1 hidden module
Child html-webpack-plugin for "index.html":
     1 asset
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 2 hidden modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!test/cases/generate-critical-css/index.css:
       [0] ./node_modules/css-loader!./test/cases/generate-critical-css/index.css 508 bytes {0} [built]
        + 1 hidden module
```

**Comment by thescientist13** [comment]
I upgraded my project [here](https://github.com/ProvidenceGeeks/website-frontend/pull/144) to use an image (one of my own that has NodeJS + needed puppeteer O.S. libs) and [it is building as expected now](https://circleci.com/gh/ProvidenceGeeks/website-frontend/331).
<img width="1517" alt="screen shot 2018-04-02 at 3 11 46 pm" src="https://user-images.githubusercontent.com/895923/38211364-37d873e2-3688-11e8-8fd3-154e43873c14.png">

I've since updated [the PR](https://github.com/thescientist13/html-critical-webpack-plugin/pull/2) and it is also [passing now](https://circleci.com/gh/thescientist13/html-critical-webpack-plugin/11).
<img width="1487" alt="screen shot 2018-04-02 at 3 25 20 pm" src="https://user-images.githubusercontent.com/895923/38211941-15127b8a-368a-11e8-8b19-d8ef232f76fb.png">

I think we should try and get CircleCI setup for this repo and merge that PR, and then rebase the webpack v4 upgrade PR.

Thoughts?

**Comment by anthonygore** [comment]
Totally. I didn't think this plugin would get so complicated, lol.

**Comment by thescientist13** [comment]
Hey @anthonygore.,

Sorry for so many threads, it took a while to get to the bottom of everything, and for better or worse, I made new issues to try and track / isolate each one, but essentially it all stems from the main issue identified in the description, which is that _all consumers of critical have to be able to support the runtime needed to run head chrome (puppeteer)_. 

This is an operating system level changes, nothing we can do at the plugin level per se aside from (IMO)
1.  Setup CI (CircleCI is free) for this project so as TO establish / document basic expectations of what is needed by consumers to use this plugin at build time (i.e. puppeteer dependency)   - #14 (would close this issue). 
1.  Number 1 should lead us down to path of reliable unit testing once the environment is normalized
1.  Complete the webpack v4 upgrade (#12 )
1.  Put out release candidate
1.  Put out release
1.  ???
1.  💰
