### ISSUE TITLE
low version webpack can't use it

### ISSUE THREAD

**Issue by meimei777** [anthonygore/html-critical-webpack-plugin#22]
can't use it in webpack version 3. will error in Compiler.hooks is undefined.hope it can compatible before version of webpack

**Comment by thescientist13** [comment]
Hi @meimei777 !

For the 2.0.0 version, this plugin moved to webpack 4+ support and above.  If you would like to use this plugin with webpack, try the [latest 1.x version](https://github.com/anthonygore/html-critical-webpack-plugin/releases)

Either way, please be aware of [this caveat](https://github.com/anthonygore/html-critical-webpack-plugin#installation).

Let me know if you have any questions!
