### ISSUE TITLE
doesn't work stripped out  critical CSS from css file.

### ISSUE THREAD

**Issue by meimei777** [anthonygore/html-critical-webpack-plugin#23]
it has work insert critical CSS with style tag in html file.but  it doesn't work stripped out  critical CSS from css file.
just add an body style in  index.css like this:
`.lazyload-wrapper .card-img {
  border-radius: 0 !important;
  min-height: 233px!important;
  max-height: 233px!important;
  object-fit: cover;
}
.fade-appear {
  opacity: 0.01;
}
.fade-appear.fade-appear-active {
  opacity: 1;
  transition: opacity 600ms ease-in; /* ms should match the value of transitionAppearTimeout */
}
body{
  background: pink;
}`
it will still have body{background:pink} in none critical css file.

**Comment by thescientist13** [comment]
Hi @meimei777 , thanks for reaching out!

Can you provide the configuration you are using for this plugin within your **webpack** config?  This plugin is essentially just [a wrapper around the **critical** CLI itself](https://github.com/anthonygore/html-critical-webpack-plugin/blob/master/src/index.js#L10), and [_should_ map options 1:1](https://github.com/anthonygore/html-critical-webpack-plugin#example).

**Comment by meimei777** [comment]
i just clone this git project to my local.  and edit index.css file add a body style.then i use webpack cli in my terminal.when i check the index.css in build file.it still have body style.

**Comment by meimei777** [comment]
In fact. Stripped out cirtical css works sometime not always.
![image](https://user-images.githubusercontent.com/13312911/41075925-880452cc-6a41-11e8-8b94-469778daf1bc.png)

![image](https://user-images.githubusercontent.com/13312911/41075902-70774c18-6a41-11e8-9e2e-27ea2369b7a4.png)
This is my configure about it:
![image](https://user-images.githubusercontent.com/13312911/41076005-e74eb3bc-6a41-11e8-945b-05357647a164.png)

**Comment by anthonygore** [comment]
I think I understand your question. The inlined critical CSS is not removed from the original CSS file, right? I think you can use the option `extract: true` to fix this.

As Owen said, this is functionality of critical and we just provide a wrapper, so you should look at it for more info https://github.com/addyosmani/critical
