### ISSUE TITLE
Ignore option is accepted?

### ISSUE THREAD

**Issue by Remeic** [anthonygore/html-critical-webpack-plugin#38]
Hi, i have some trouble with font paths and i want to exclude the css rules for them.
From addy criticalcss repo i see there is a ignore option, that i copy and paste in my 'html-critical-webpack-plugin' options like this:

`new HtmlCriticalWebpackPlugin({
      base: path.join(path.resolve(__dirname)),
      src: '../website/templates/website/home.html',
      dest: '../build/css/critical.css',
      inline: false,
      minify: true,
      extract: true,
      penthouse: {
        blockJSRequests: false,
      },
      ignore: {
        atrule: ['@font-face']
      }
    })`

But seems doesn't work, because i find again font-face rules

**Comment by Tim152** [comment]
It's work in my case:
```
ignore: ['@font-face'],
```

**Comment by Remeic** [comment]
Yes, with this syntax works perfectly @Tim152
