### ISSUE TITLE
Generated inline styles are wrong

### ISSUE THREAD

**Issue by Tim152** [anthonygore/html-critical-webpack-plugin#39]
Hello! I have SPA (vue + vue cli), after build, I get styles from another page, my main page (`/`, -> redirect to `/signin`) contains only auth form, simple header, footer, logo (look at example of using styles in screenshot) and it can't pass you next page, until you Sign In
<img width="901" alt="Screenshot 2019-06-05 at 13 44 25" src="https://user-images.githubusercontent.com/14087100/58951127-0a0ed100-8799-11e9-8171-4f8edbf267de.png">

But, my generated inline styles are from protected page (for authorized users)
How is it happen?
Puppeteer can't auth on it own, but seems it get protected page for generated styles, can I control somehow generating process for watching Pupeteer work, console?(might be getting Promise in config?).

My vue.config.js

```
  configureWebpack: config => {
    if (process.env.NODE_ENV === 'production') {
      config.plugins.push(
        new HtmlCriticalWebpackPlugin({
          base: path.resolve(__dirname, 'dist'),
          src: 'index.html',
          dest: 'index.html',
          inline: true,
          minify: true,
          width: 1200,
          height: 900,
          ignore: ['@font-face'],
          penthouse: {
            blockJSRequests: false
          }
        })
      );
    }
  },
```

Any suggestions?

**Comment by thescientist13** [comment]
I would see some other related open issues, it's not clear how well critical itself works with SPA, since all the HTML is generated dynamically.  
- #31 
- #29 
- #27 (potential solution, not sure how viable it actually is)


Can you confirm if running `critical` directly from the command line produces different (better / expected) results?

**Comment by Tim152** [comment]
@thescientist13 Thank you for respond! 
Unfortunately no, `critical`  directly from command line produces exactly the same wrong result, seems like it's not plugins fault..
