### ISSUE TITLE
Output is full html and not css

### ISSUE THREAD

**Issue by alikazai** [anthonygore/html-critical-webpack-plugin#42]
Hi i am having some issues trying to implement this plugin into my pipeline. it seems the file being outputed is a full html file and not just a pure css. and when i set the destination to my cshtml file it seems to overwrite it with a html dump of the live page.

is there a way to only get the style and not the full html. i used to use the grunt version of critical css which generates the styles only.

this is the setup..
umbraco Cms
asp.net

want the plugin to generates a critical css file which i can insert as a partial into the cshtml template file.

my config is:
```
new HtmlCriticalPlugin({
        base: 'dist/',
        src: 'http://localhost:55778/business/',
        dest: 'file.min.css',
        inline: true,
        minify: true,
        extract: false,
        width: 1920,
        height: 900,
        penthouse: {
            blockJSRequests: false,
        }
    })
```

thanks

**Comment by alikazai** [comment]
Hi thanks i found the issue i had inline set to true which was generating the html aswell. once i set it to false it was outputting the css only.

thanks

**Comment by thescientist13** [comment]
great, glad to hear you got it working.  👍
