### ISSUE TITLE
Is there a way to use this with next js?

### ISSUE THREAD

**Issue by sanishkr** [anthonygore/html-critical-webpack-plugin#43]
Can someone please provide an example repo?

**Comment by thescientist13** [comment]
I don't really know enough about Next.js to answer though unfortunately, or if it has it's own ecosystem tool(s) for that.

That said, if you have access to the **webpack** configuration, then it should be possible, in theory

**Comment by js-sapphire** [comment]
Can we re-open this issue? 
I am trying to extract critical css in a next project with tailwind-css. Currently, the build step generates 1 bundle ( ~16Kb ) which has all the purged classnames from tailwind-css. How can I use this plugin in a next project ?

**Comment by markoleavy** [comment]
@js-sapphire did you solved somehow this issue?
