### ISSUE TITLE
Any way to run critical with a local html file loading local javascript?

### ISSUE THREAD

**Issue by bfkeinberg** [anthonygore/html-critical-webpack-plugin#7]
I've been trying to run critical to optimize the load time of my SPA. The problem is that I need my js to load to render the page, and it seems to not load unless I hand edit the html page to put the full local file path of my javascript bundle into the html.  If I don't do that then the css is generated for an empty page. I debugged this by adding in the parameters for penthouse to do a before and after screenshot. 
Has anyone else encountered this or am I the only one?
I know that it would be better to go with server side rendering and avoid all this but as I'm just using flask for my project switching to node.js and all that is a ways off for me...

**Comment by anthonygore** [comment]
Hey, could you provide a repo with a [reduced test case](https://css-tricks.com/reduced-test-cases/) for this scenario? Then I/someone can run it locally and try to debug. Thanks!

**Comment by bfkeinberg** [comment]
In the process of creating my reduced test case, I found that the actual root cause was a combination of setting publicPath in webpack to a value with a leading slash (breaks critical somehow?) and having some js that tried to set the url via history and broke under chromium. So no issue here. :)
